ccflags-y += -Idrivers/media/platform/msm/camera_v2_moto
ccflags-y += -Idrivers/media/platform/msm/camera_v2_moto/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_moto/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
