ccflags-y += -Idrivers/media/platform/msm/camera_v2_moto
ccflags-y += -Idrivers/media/platform/msm/camera_v2_moto/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_moto/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
