ccflags-y += -Idrivers/media/platform/msm/camera_v2_moto
ccflags-y += -Idrivers/media/platform/msm/camera_v2_moto/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_led_flash.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_trigger.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_i2c_trigger.o
obj-$(CONFIG_LEDS_ADP1660) += adp1660.o
obj-$(CONFIG_LEDS_LM3646) += lm3646.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_torch.o
